---
- name: "add application users"
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - vars/ssh_keys.yml
  tasks:
    - name: Create application users
      user:
        name: "{{ item }}"
        append: yes
        createhome: yes
        shell: /bin/bash
        state: present
      with_items: "{{ app_users }}"
