---
- name: "configure hostname"
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: "fill /etc/hostname"
      copy:
        content: "{{ hostname }}\n"
        dest: "/etc/hostname"