# As per https://docs.docker.com/engine/install/ubuntu/
---
- hosts: all
  name: Install Docker
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Docker apt key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
        warn: false # don't warn on curl

    - name: Create a list file for Docker
      copy: # Ubuntu 18.04 (Bionic)
        content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable"
        dest: "/etc/apt/sources.list.d/docker.list"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
