---
- hosts: all
  name: Install certbot
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
#    - name: Update apt cache
#      apt:
#        update_cache: yes

    - name: 'Check certbot is installed'
      shell: |
        if [ -x '/usr/bin/certbot' ]
        then
          echo "$(/usr/bin/certbot --version) is installed"
          exit 1
        else
          echo 'certbot will be installed...'
        fi
      register: okToInstallCertbot
      ignore_errors: True
    - debug: var=okToInstallCertbot

    - name: 'Install certbot'
      when: okToInstallCertbot is succeeded
      # https://certbot.eff.org/instructions?ws=other&os=ubuntubionic
      shell: |
        sudo snap install core; sudo snap refresh core
        sudo snap install --classic certbot
        sudo ln -s /snap/bin/certbot /usr/bin/certbot
        echo
        echo "$(/usr/bin/certbot --version) is installed"
      register: res
      ignore_errors: True

    - debug: var=res
      when: okToInstallCertbot is succeeded

