---
- hosts: all
  name: Install yt-dlp
  become: true
  become_method: sudo
  vars:
    # The path where yt-dlp executable will be installed.
    # It is recommended to not change this path.
    ytdlp_executable_path: "/usr/local/bin/yt-dlp"

    # Do we need to update yt-dlp if it is already installed?
    ytdlp_update: false
  tasks:
    - name: Make python = python3
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3

    - name: Check if yt-dlp is already installed
      stat:
        path: "{{ ytdlp_executable_path }}"
      register: ytdlp_bin

    - name: Download from source move to executables folder and set permissions
      get_url:
        url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
        dest: "{{ ytdlp_executable_path }}"
        mode: 0755
        force: yes
      when: not ytdlp_bin.stat.exists

    - name: Update yt-dlp
      command: yt-dlp -U
      register: ytdlp_update_out
      when: ytdlp_bin.stat.exists and ytdlp_update
      changed_when: "'Updated yt-dlp.' in ytdlp_update_out.stdout"
      failed_when: "'ERROR:' in ytdlp_update_out.stdout"
      ignore_errors: true