---
- hosts: all
  name: Install useful utils
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install utils
      apt:
        pkg:
          - jq
          - ncdu
          - pv

    - name: Jsqry
      get_url:
        url: "https://github.com/jsqry/jsqry-cli2/releases/download/v0.1.2/jsqry-linux-amd64"
        dest: "/usr/local/bin/jsqry"
        mode: 0755
