---
- hosts: all
  name: Install web servers soft
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install soft
      apt:
        pkg:
          - haproxy
          # if smth goes wrong: `sudo apt purge nginx-common nginx` first
          # https://askubuntu.com/a/728786/222919
          - nginx
